export enum EActions {
  CARD_LIST_REQUEST = 'CARD_LIST_REQUEST',
  CARD_LIST_REQUEST_SUCCESS = 'CARD_LIST_REQUEST_SUCCESS',
  CARD_LIST_REQUEST_ERROR = 'CARD_LIST_REQUEST_ERROR',
  ADD_TO_FAVORITES = 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES',
}
